version: 0.0
os: linux
files:
  - source: build/
    destination: /var/www/html/
    overwrite: yes
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 150
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 10
      runas: root
