version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo 'install dependencies'
      - npm install

  build:
    commands:
      - echo 'building the project'
      - npm run build

artifacts:
  files:
    - "public/**/*"
