version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies
      - npm install

  pre_build:
    commands:
      - echo Pre-build phase

  build:
    commands:
    on-failure: ABORT 
      - echo Building the project
      - ls -l
      - npm run build

artifacts:
  files:
    - "build/**/*"
